### ISSUE TITLE
Using vue2 for Multiple slide when on last slide it does not slide if click Prev

### ISSUE THREAD

**Issue by stripathix** [bartdominiak/vue-snap#76] opened 2022-05-09 06:38 UTC
Using vue2 for Multiple slides when on the last slide it does not slide if click Prev

Code Sandbox: https://codesandbox.io/s/vue-2-playground-forked-l1jg4w?file=/src/App.vue
Demo: https://l1jg4w.csb.app/

Steps:
Scroll to the end and then click on the Prev button you have to click 4 times to move the slide.

<img width="1279" alt="Screenshot 2022-05-09 at 3 18 54 PM" src="https://user-images.githubusercontent.com/8480351/167385283-22478b76-202f-4c80-bf29-d0acd983435a.png">

**Comment by pablogiralt** [comment] 2022-06-28 10:58
same issue here.  I need to click twice for it to work

**Comment by pablogiralt** [comment] 2022-06-28 10:59
I believe this is duplicate of https://github.com/bartdominiak/vue-snap/issues/62

**Comment by pablogiralt** [comment] 2022-06-28 14:50
fixed in this fork https://github.com/peanut-butter-co/vue-snap

credit to @iosamuel who had this same fix in his fork but had other stuff which I did not need

**Closed** 2022-12-05 14:34 UTC
